### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by karfau** [thechangelog/show-notes#168]
The link to the "Urgency Importance Matrix" in https://github.com/thechangelog/show-notes/blob/master/jsparty/js-party-187.md is broken.

of course its possible to search for the topic, but there are quite some different resources on the topic.
Might make sense to link to some resource (maybe a website on the topic, not just an image) that is aligned with the previously linked image.

**Comment by jerodsanto** [comment]
@karfau the link works for me, but I will go ahead and download/re-host it just in case it ever does disappear. Fix incoming!
