### ISSUE TITLE
Policy regarding show note items

### ISSUE THREAD

**Issue by hhrutter** [thechangelog/show-notes#2]
Many times the show notes are prepared prior to recording
and sometimes prepared links don't get mentioned in the show for one or another reason.

What's our policy regarding these links. Should we scratch them so that the show notes only reflect items mentioned during the show or leave them in anyway.

eg. the GoTimeFM team sometimes prepares links to interesting projects that don't make it into the show due to lack of recording time.

**Comment by jerodsanto** [comment]
Good question! Let's go with the former (scratch them) so that the notes accurately reflect the show's final content, not the planned content.

Maybe this would be a good start to a "Guidelines" sub-section in the readme?

**Comment by hhrutter** [comment]
Your call.
I can take care of that.
Do I need to submit a PR to get the commit flag?

**Comment by jerodsanto** [comment]
1. Added you.
2. I think a Guidelines section would be useful. Let's start one.
3. Yeah, purging dead links is 👌
