### ISSUE TITLE
chore: missing links in Don't make things worse episode

### ISSUE THREAD

**Issue by schalkneethling** [thechangelog/show-notes#229]
The last two Youtube links in the show notes for this episode link to youtube.com/watch instead of the Youtube videos referenced by the links. I believe the links should be:

- https://youtu.be/GRr4xeMn1uU
- This one is tricky and does not seem to be online anymore - https://web.archive.org/web/20201101001905/https://vimeo.com/108441214
- There is this Gitlab page that seems to share some notes from the video: https://gitlab.com/vargavince91/yt-notes/-/issues/1

Happy to send a PR if we can agree on what to link to.

**Comment by jerodsanto** [comment]
Good catch! I had both URLs in my browser history, just somehow lost the video id when pasting into the show notes. Fixed now!
